### ISSUE TITLE
[bug] special character in message

### ISSUE THREAD

**Issue by AliMD** [Briuor/wbm#10]
Thank you so much for making this greate tools
I cant sent `+` in the message!
Any solution?

**Comment by Briuor** [comment]
Thank you for this issue, i released a fix for it. Update your package 
```sh
npm update wbm
```
and test again.
I was using the method **encodeURI()** to encode the message and send as an url parameter, but this method don't encode characters like '+', '&', '=', i changed to **encodeURIComponent()** that encode all characters.

**Comment by alwinsajip** [comment]
Could you please look into the
issue #11
