### ISSUE TITLE
Error !

### ISSUE THREAD

**Issue by Mr4FX** [Briuor/wbm#12]
hello,
when i try to install wbm it shows me this error : 

![image](https://user-images.githubusercontent.com/45691910/95092033-13a6a100-071f-11eb-9bb9-e3a2520dc6a1.png)

can you please tell me why ?
thanks.

**Comment by Briuor** [comment]
@Mr4FX It's a npm error, the error message ask if you name the project the same as the dependency, you should **change your project name**, because as i can see your project folder name is wbm too, change it to your project name.

**Comment by Mr4FX** [comment]
i did git clone of your project and git saved it automatically by name "wbm" should i rename the folder ?

**Comment by Briuor** [comment]
As you cloned you don't need to use npm install(you can use it to install wbm in a project as a npm package). 
There is a file called test.js inside the project, just change the phone numbers inside this file and run the command:
```sh
node test.js
```

**Comment by Mr4FX** [comment]
check this issue
![image](https://user-images.githubusercontent.com/45691910/95142770-6195c600-076c-11eb-84dc-86c8c4828bcf.png)
i using google cloud

**Comment by Briuor** [comment]
wbm uses puppeteer(a google library for web automation) and puppeteer download the chromium browser to do it, looking at the error i think the chromium browser wasn't downloaded, so to solve it:
- install a chrome or chromium [this link can help](https://askubuntu.com/questions/79280/how-to-install-chrome-browser-properly-via-command-line)
- inside **wbm/src/api.js line 21** insert the **executablePath: 'CHROME_DOWNLOADED_PATH'** like below.
```js
// ...
const args = {
        headless: !showBrowser,
        userDataDir: tmpPath,
        executablePath: '/path/to/Chrome', // PATH TO CHROME DOWNLOADED
        args: ["--no-sandbox",
            // "--blink-settings=imagesEnabled=false"]
        ]
    }
```
I will create an easy way to configure chrome in a next release.
