### ISSUE TITLE
stopped working

### ISSUE THREAD

**Issue by valessiobrito** [Briuor/wbm#13]
My application runs correct, connects but does not send msg.

In test.js mode it loops, loses the connection after authentication is done and doesn't send the message.

---

Minha aplicação esta rodando corretamente, mas ela conecta e não envia as mensagens;
No modo test.js, o navegador é aberto, autenticado, fica em loop (reiniciando) e não envia a mensagem.

Alguma dica?

**Comment by Briuor** [comment]
Opa @valessiobrito obrigado por abrir essa issue, rodei aqui e realmente não estava enviando as mensagens. É raro mas as vezes o código do whatsapp web muda e aparece alguns bugs hehe. Mas ja resolvi já aqui, só atualizar a lib e rodar:

```sh
# comando para atualizar a lib
npm update wbm
```
Se tiver algum problema é só avisar aqui. Vlw, grande abraço!

**Comment by valessiobrito** [comment]
Gratidão.  Funcionando.

**Comment by valessiobrito** [comment]
@Briuor não estou conseguindo debugar; mas tem um comportamente estranho ocorrendo.   Ele envia mensagem somente se a pessoa estiver na minha lista de contatos recentes;   Se ainda estiver na agenda, ele não consegue enviar.  (acho que isso).

Ele diz que mensagens foram enviadas, mas na verdade não foi concluido o envio.  O intervalo/tempo pode esta muito curto para renderizar a tela e enviar a msg.   Continuo tentando debugar.
