### ISSUE TITLE
[features] Sending an image or audio

### ISSUE THREAD

**Issue by valessiobrito** [Briuor/wbm#14]
I'm not good at programming. I'm trying to adapt the code to send an attachment or audio. I'm not getting. Any tips?

const message = fs.readFileSync('photo.jpg');   

it's not the expected result.

**Comment by Briuor** [comment]
**wbm** still not support sending images or audios.
I'm not having too much time to work on new features, but for sure the next feature is allow sending images.
I've tried implementing it before but it wasn't easy as i thought.

The project [whatsapp-web.js](https://github.com/pedroslopez/whatsapp-web.js) is about whatsapp automation too and it allows sending images. Maybe it can help you.

**Comment by valessiobrito** [comment]
Thanks for answering. I think it will work.
