### ISSUE TITLE
Not working when application is hosted

### ISSUE THREAD

**Issue by AkshaySyal** [Briuor/wbm#16]
The web application I made using wbm was working locally. But when I hosted on heroku it is not working.

**Comment by Briuor** [comment]
Does it throw an error message? Can you paste the error here?
If the error message is like this:
```sh
/home/user/erp/node_modules/puppeteer/.local-chromium/linux-555668/chrome-linux/chrome: 
error while loading shared libraries: libX11-xcb.so.1: cannot open shared object file: No such file or directory
```
You can try this solution:
https://medium.com/@ssmak/how-to-fix-puppetteer-error-while-loading-shared-libraries-libx11-xcb-so-1-c1918b75acc3

I'm not maintaining wbm anymore, sorry about that.
