### ISSUE TITLE
I can not send messages

### ISSUE THREAD

**Issue by CactusWingsMX** [Briuor/wbm#17]
I try to send messages to the default number, could you help me please
![image](https://user-images.githubusercontent.com/67400844/111874084-1e659300-8959-11eb-80a3-a3a99681afa2.png)

**Comment by woodsbox** [comment]
The problem is in the api.js on line 153:

await page.waitForSelector('#main > footer > div._3SvgF._1mHgA.copyable-area > div.DuUXI > div > div._1awRl.copyable-text.selectable-text', { timeout: 5000 });

This piece of code is not working anymore.

**Comment by Briuor** [comment]
Nice @woodsbox. Fixed in wbm 1.1.14

**Comment by woodsbox** [comment]
Maybe just a small tip put also on line 163: console.log(err);
