### ISSUE TITLE
Seems like it does not work. 

### ISSUE THREAD

**Issue by pramod0** [Briuor/wbm#2]
I tried this with my electron-vue app. I see QR code in console log but my WhatsApp web can't scan it. Is there a specific way to make this work?
<img width="607" alt="Screenshot 2020-03-18 at 2 53 30 AM" src="https://user-images.githubusercontent.com/1523039/76903261-bc94c800-68c3-11ea-831f-9de5ccf6d14f.png">

**Comment by Briuor** [comment]
Hi @pramod0, did you install wbm using npm or downloading the repository? I'm asking it because the version on github was not updated yet. Can you please check wbm version in your package.json?

**Comment by pramod0** [comment]
Thanks for quick reply. I installed using npm. The version is "wbm": "^1.0.6"

**Comment by pramod0** [comment]
I can give you access.

**Comment by Briuor** [comment]
### Original Whatsapp Web QR Code
![Screenshot from 2020-03-20 18-36-35](https://user-images.githubusercontent.com/31521275/77208421-82e9da00-6ada-11ea-93b4-3409b38cac9a.png)

### QR Code generated on command line
![Screenshot from 2020-03-20 18-38-13](https://user-images.githubusercontent.com/31521275/77208590-e542da80-6ada-11ea-9d86-741e323ec68e.png)

### QR Code generated on browser console
![Screenshot from 2020-03-20 18-39-11](https://user-images.githubusercontent.com/31521275/77208629-00154f00-6adb-11ea-9ad2-f0118bd1c907.png)

### The problem
When it is displayed on **browser console** the color is inverted(what is white becomes black and vice-versa) and can't be scanned.

### Solution
To solve your problem i've created a method that returns the whatsapp web QR Code data, so you can use this data to generate your own QR Code on browser(i found this library that do it for you https://davidshimjs.github.io/qrcodejs/)

So you can use like this:
```js
wbm.start({ qrCodeData: true }).then(async qrCodeData => {
    console.log('QRCode data: ', qrCodeData); // use this data to generate your own qrcode
    // here you generate your own qrcode(you can use this https://davidshimjs.github.io/qrcodejs/)
    await wbm.waitQRCode(); // it's used to avoid qrcode errors
    await wbm.send(phones, message);
});
```

**Comment by LuizTokuhara** [comment]
> I tried this with my electron-vue app. I see QR code in console log but my WhatsApp web can't scan it. Is there a specific way to make this work?
> <img alt="Screenshot 2020-03-18 at 2 53 30 AM" width="607" src="https://user-images.githubusercontent.com/1523039/76903261-bc94c800-68c3-11ea-831f-9de5ccf6d14f.png">

Hi, could you describe how you run wbm with electron?

Regards,
Luiz

**Comment by AdiletArykbaev** [comment]
hello why on logs it seems like i was sended,but not come,how can i fixe it

**Comment by kazim-asif** [comment]
QR code is being generated but on scanning through WhatsApp, I am unable to login. It says that can't linked the device. It is not working
