### ISSUE TITLE
Cannot Send Messages

### ISSUE THREAD

**Issue by manankarani** [Briuor/wbm#24]
I think there is a recent change, worked few days ago, but right now it fails.

Bug is on line 162
`await page.waitForSelector(SELECTORS.SEND_BUTTON, { timeout: 5000 });`

I think that the Selector value needs to be updated:
`SEND_BUTTON: 'div:nth-child(3) > button > span[data-icon="send"]'` 
this one fails currently

**Comment by balataca** [comment]
I've updated the send button selector and it seems to be working now.

**Comment by juliohsu** [comment]
It still not working!

**Comment by juliohsu** [comment]
I am trying to send a message, but it just doesnt send

**Comment by balataca** [comment]
I am not the owner of this repository so I've made a pull request to integrate my changes, but the owner has to approve it and then merge and build a new npm package. If you don't want to wait check out my pull request [here](https://github.com/Briuor/wbm/pull/25) and integrate the changes locally.

**Comment by Briuor** [comment]
@balataca PR was merged, nice fix! Fix present on version 1.1.16
```sh
npm update wbm
```
