### ISSUE TITLE
limite msgs

### ISSUE THREAD

**Issue by PedroPCardoso** [Briuor/wbm#3]
What limit of messages sent per day?

**Comment by Briuor** [comment]
wbm is an **unofficial** solution and whatsapp don't agree with it. Use with moderation, personally i think it's secure send around 200 ~ 300 messages per day. If using as a solution for a company, don't use wbm,  try a paid one.

**Comment by valessiobrito** [comment]
Official limits:  https://developers.facebook.com/docs/whatsapp/api/rate-limits/
