### ISSUE TITLE
 Message sent successfully in logs but not received

### ISSUE THREAD

**Issue by anhtuanatc** [Briuor/wbm#30]
Message sent successfully in logs but not received.
I also checked in the phone app and there is no message sent.

**Comment by anhtuanatc** [comment]
I open the browser (showBrowser:true) , I see the message initialization but stop at the chat frame and don't click the send button

**Comment by balataca** [comment]
Hello,

I've tested here with the  wbm version `1.1.16` and it seems to work. Could you inspect the send button and double check if the Puppeteer selector is correct?

To check the selector open the file`node_modules/wbm/src/api.js` and check/change the constant `SEND_BUTTON` with the correct css selector:
```
SEND_BUTTON: 'div:nth-child(2) > button > span[data-icon="send"]'
```

**Comment by anhtuanatc** [comment]
Thank you for help.
I use version 1.1.16 now. and check correct css selector SEND_BUTTON.
I change page.waitFor(1000) -> page.waitFor(10000) then can send first 2 numbers in list of 4 numbers.
2 numbers after the browser stops at texting doesn't press the send button.
I use server window10 2016 have 4gb ram and 2 core

**Comment by balataca** [comment]
So have you solved your issue? If yes, could you please close this issue?

**Comment by anhtuanatc** [comment]
I'm trying to solve the problem, maybe it's the server's network or puppeteer.
