### ISSUE TITLE
Session not saving

### ISSUE THREAD

**Issue by ryanisho** [Briuor/wbm#43]
Requiring me to re-authenticate through QR code every message sent. Already tried turning session argument to false, then back to true; did not work. Also reinstalled dependency. Application currently hosted on Amazon AWS EC2 Instance.

Any thoughts would be greatly appreciated.

**Comment by isaacmeira** [comment]
did you solve it @ryanisho  ?

**Comment by ryanisho** [comment]
I did not - I ended up just not doing it.
