### ISSUE TITLE
Do you have any plan to give a web interface to scan QR code and select mobile number csv 

### ISSUE THREAD

**Issue by kshyam** [Briuor/wbm#9]
New Feature Request - Do you have any plan to give a web interface to scan QR code and select mobile number csv, amd message input. with Images.

**Comment by Briuor** [comment]
I'm working on some new features that are improve performance, a better code architecture, parameters to set a random interval to send messages, and send media(documents, images).
To send messages to numbers from a csv file you can use another npm package like [csv-wp](https://www.npmjs.com/package/csv-wp) that extract the numbers and pass the array of number/contacts to wbm.
I'm not planing creating a web interface to scan QR code, but i can create it in a future release.
